name: Java Dominicano Monthly Talk Proposal
description: Enviar propuesta para las reuniones mensuales de la comunidad Java de República Dominicana.
title: "[Proposal] Título de la propuesta"
labels: [Proposal, Talk]
body:
- type: markdown
  attributes:
      value: |
        Si estás interesado en realizar una charla en la comunidad Java de República Dominicana, por favor, completar las siguientes informaciones.
- type: input
  attributes:
    label: Título
  validations:
     required: true
- type: input
  attributes:
    label: Fecha
  validations:
     required: true   
- type: input
  attributes:
    label: Hora
  validations:
     required: true        
- type: textarea
  attributes:
    label: Descripción
    description: Agregue una descripción detallada del tema que desea tratar.
  validations:
    required: true
- type: textarea
  attributes:
    label: Bio
    description: |
      Agregue datos relevante sobre su vida profesional.
      Nota: Agregar algún enlace de su cuenta de github, GitLab, BitBucket o cualquier otra plataforma que contenga su portafolio en línea.
  validations:
    required: true
